# Production deployment
deploy-mainnet-production-full :; ENV=production forge script script/Deploy.s.sol:DeployMainnetFull --sender ${ETH_FROM} --account deployer --broadcast --verify

# Staging deployment
deploy-mainnet-staging-full :; ENV=staging forge script script/Deploy.s.sol:DeployMainnetFull --sender ${ETH_FROM} --account deployer --broadcast --verify
